window:
  width: 450
  height: 200

notifications:
  information:
      hours: 7
  warning:
      hours: 8
  critical:
      hours: 9

assets:
  root: pycounter/assets/
  icon: icon.svg
  pause: pause.svg
  play: play.svg
  reset: reset.svg
  quit: quit.svg
  push: push.svg
  stylesheet: style.qss

mind:
  database: 'test'
  collection: 'herecomestheuser'
  defaultorder: "1234"

